services:
  frontend:
    image: frontend_dev
    container_name: frontend_container_dev
    depends_on:
      - "backend"
    ports:
      - "3001:3001"
    environment:
      - VITE_BASE_URL=http://backend_container:4000
  frontend_test:
    image: frontend_dev
    container_name: frontend_test
    depends_on:
      - "frontend"
    stdin_open: true
    tty: true
    command: yarn run test
  backend:
    image: backend
    container_name: backend_container
    depends_on:
      - "db"
    ports:
      - "4000:4000"
  backend_test:
    image: backend
    container_name: backend_test
    depends_on:
      - "db"
    stdin_open: true
    tty: true
    command: go test -v ./...
  db:
    image: jaypeng2015/show-me-the-money
    container_name: demyst_db
    ports:
      - "3000:3000"
